name: FontLab CI Export on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    outputs:
      fontlab_version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get FontLab Version
        id: get_version
        run: |
          $url = "https://download.fontlab.com/fontlab-8/upd-win64.php"
          $response = Invoke-WebRequest -Uri $url -Headers @{"Accept-Language"="en-US,en;q=0.9"} -UserAgent "Mozilla/5.0" -MaximumRedirection 0 -ErrorAction SilentlyContinue -SkipHttpErrorCheck
          $redirectUrl = $response.Headers['Location']
          if ($null -eq $redirectUrl) {
              throw "Could not find the redirect URL in the response headers."
          }
          $version = [System.IO.Path]::GetFileName($redirectUrl).Replace('FontLab-8-Win64-Install-', '').Replace('.exe', '')
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Cache FontLab Installer
        id: cache-installer
        uses: actions/cache@v2
        with:
          path: |
            FontLab-Installer.exe
          key: ${{ runner.os }}-fontlab-installer-${{ steps.get_version.outputs.version }}

      - name: Download FontLab
        if: steps.cache-installer.outputs.cache-hit != 'true'
        run: |
          $url = "https://download.fontlab.com/fontlab-8/upd-win64.php"
          $output = "FontLab-Installer.exe"
          Invoke-WebRequest -Uri $url -Headers @{"Accept-Language"="en-US,en;q=0.9"} -UserAgent "Mozilla/5.0" -OutFile $output

      - name: Install FontLab
        run: |
          $installer = Get-ChildItem -Path . -Filter "FontLab-Installer.exe" | Select-Object -ExpandProperty FullName
          Start-Process -FilePath "$installer" -ArgumentList "/NOCANCEL /SP- /VERYSILENT /SUPPRESSMSGBOXES" -Wait

      - name: Prep FontLab data folder
        run: |
          $fontlabUserDir = Join-Path "$env:APPDATA" "FontLab\\FontLab 8"
          Write-Output "FontLab directory: $fontlabUserDir"
          if (-not (Test-Path "$fontlabUserDir")) {
              New-Item -ItemType Directory -Path "$fontlabUserDir" -Force
          }
          Copy-Item -Path "scripts\\startupScript.py" -Destination "$fontlabUserDir"
          tree /F $env:APPDATA

      - name: Run Build Script
        run: |
          $fontLabExe = "C:\\Program Files\\FontLab\\FontLab 8\\FontLab 8.exe"
          $scriptPath = "scripts\\fontlab_export.vfpy"
          $configPath = "scripts\\fontlab_build.yaml"
          $arguments = @("$scriptPath", "$configPath")
          $process = Start-Process -FilePath "$fontLabExe" -ArgumentList "$scriptPath" -PassThru
          $timeout = New-Timespan -Seconds 300
          $sw = [Diagnostics.Stopwatch]::StartNew()
          while ($sw.Elapsed -lt $timeout) {
              if ($process.HasExited) {
                  break
              }
              Start-Sleep -Seconds 5
          }
          if (-not $process.HasExited) {
              $process | Stop-Process -Force
              Write-Error "Process timed out."
          }

      - name: Test Exported Fonts
        run: |
          # Add your testing commands here

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Commit and Push Exported Fonts
        run: |
          $outputDirectory = "build"
          $distDirectory = "fonts"
          if (Test-Path "$outputDirectory") {
              Move-Item -Path "$outputDirectory\\*.ttf" -Destination "$distDirectory"
          }
          git add "$distDirectory\\*.ttf"
          $commit = git commit -m "Update exported fonts"
          if ($commit -ne $null) {
              git push
          } else {
              Write-Output "No new fonts to commit"
          }
